--Operações Básicas
SELECT 25
SELECT 'SENAI'
SELECT '21/05/2024'

--OPERAÇÕES COM NÚMEROS
SELECT 30+20 AS 'SOMA'
SELECT 30-20 AS 'SUBTRAI'
SELECT 30*20 AS 'MULTIPLICA'
SELECT 30/20 AS 'DIVIDE'
SELECT 30.0/20 AS 'DIVIDE'

--OPERAÇÕES COM TEXTOS
SELECT 'ISMAEL' + 'ALVES'
SELECT 'ISMAEL' + ' ALVES'

--OPERAÇÕES COMDATAS
SELECT '20/05/2024' + 1 --(ERRO)

--1) SQL_VARIANT_PROPERTY

SELECT SQL_VARIANT_PROPERTY(10, 'BaseType')
SELECT SQL_VARIANT_PROPERTY(51.45, 'BaseType')
SELECT SQL_VARIANT_PROPERTY('Ismael', 'BaseType')
SELECT SQL_VARIANT_PROPERTY('21/05/2024', 'BaseType')

--2) CAST: Função para especificar tipos os dados
SELECT SQL_VARIANT_PROPERTY(CAST(50.46 AS INT), 'BaseType')
SELECT SQL_VARIANT_PROPERTY(CAST(50.46 AS FLOAT), 'BaseType')
SELECT SQL_VARIANT_PROPERTY(CAST(72.72 AS FLOAT), 'BaseType')
SELECT SQL_VARIANT_PROPERTY(CAST('82.50' AS FLOAT), 'BaseType')
SELECT SQL_VARIANT_PROPERTY(CAST('21/05/2024' AS DATETIME), 'BaseType')

--EX1) Crie uma consulta juntando o texto '1ª PARCELA DE' com o valor 350.25



SELECT '1ª PARCELA DE' + ' ' + CAST(350.25 AS VARCHAR)

--EX2) Adicione 10 à data '21/05/2024'


SELECT 10 + CAST('21/05/2024' AS DATETIME)



--EX3) FORMAT: Função para formatação de valores no SQL

--a) Numéricos:
SELECT FORMAT(3000, 'N') --number
SELECT FORMAT(3000, 'G') --Geral

--b) Personalizados:
SELECT FORMAT(12345678905, '###-###-###-##')

--c) Data:
SELECT FORMAT(CAST('20/05/2024' AS DATETIME), 'dd/MM/yyyy')
SELECT FORMAT(CAST('20/05/2024' AS DATETIME), 'dd/MMM/yyyy')
SELECT FORMAT(CAST('20/05/2024' AS DATETIME), 'dd/MMMM/yyyy')
SELECT FORMAT(CAST('20/05/2024' AS DATETIME), 'ddd')
SELECT FORMAT(CAST('20/05/2024' AS DATETIME), 'dddd')

--EX4) Crie uma consulta juntando o texto 'Data de validade' 12/jun/2024.

SELECT 'Data de validade ' + FORMAT(CAST('12/06/2024' AS DATETIME), 'dd/MMM/yyyy')