--     Funções de arredondamento

--ROUND
SELECT ROUND(10.0/6, 2)


--ROUND(Truncar)
SELECT ROUND(10.0/6, 2, 1)  --(0)REGRA MAT. (1) CORTE

--FLOOR
SELECT FLOOR(120.8)   --ARREDONDA PARA BAIXO

--CEILING
SELECT CEILING(120.8) --ARREDONDA PARA CIMA